# setup environment
dist: jammy
language: ruby

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
  - APM_TEST_PACKAGES='language-ruby'
  - ATOM_LINT_WITH_BUNDLED_NODE='true'
  - VERSION='2.2.19'

os: linux

# execute tests
install:
  - sudo wget "https://releases.hashicorp.com/vagrant/${VERSION}/vagrant_${VERSION}_x86_64.deb"
  - sudo dpkg -i "vagrant_${VERSION}_x86_64.deb"
before_script: vagrant --version
script: 'curl -s https://raw.githubusercontent.com/mschuchard/vagrant-boxes-docker-images/master/atom-build-package.sh | sh'
