# setup environment
sudo: false
language: ruby

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
    - APM_TEST_PACKAGES="language-ruby"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

matrix:
  include:
  - os: linux
  - os: linux
    env: ATOM_CHANNEL=beta

# execute tests
install: dpkg -i https://releases.hashicorp.com/vagrant/1.9.4/vagrant_1.9.4_x86_64.deb
before_script: vagrant --version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
