# vm:
# * The following settings shouldn't exist: bix
# * A box must be specified.
#
# Vagrant:
# * Unknown configuration section 'vb'.
Vagrant.configure('2') do |config|
  config.vm.bix = 'hashicorp/precise64'
  config.vb.foo = 'what'
end
