# There was an error loading a Vagrantfile. The file being loaded
# and the error message are shown below. This is usually caused by
# a syntax error.

# Path: <provider config: virtualbox>
# Line number: 5
# Message: NameError: undefined local variable or method `vb' for main:Object
Vagrant.configure('2') do |config|
  config.vm.box = 'hashicorp/precise64'

  config.vm.provider 'virtualbox' do |foo|
    vb.cpus = '2'
  end
end
